// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: auth_dto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cerberos.TfaImporter.DTO.Proto {

  /// <summary>Holder for reflection information generated from auth_dto.proto</summary>
  internal static partial class AuthDtoReflection {

    #region Descriptor
    /// <summary>File descriptor for auth_dto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthDtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5hdXRoX2R0by5wcm90bxIPZ29vZ2xlLnByb3RvYnVmItwFChBNaWdyYXRp",
            "b25QYXlsb2FkEkcKDm90cF9wYXJhbWV0ZXJzGAEgAygLMi8uZ29vZ2xlLnBy",
            "b3RvYnVmLk1pZ3JhdGlvblBheWxvYWQuT3RwUGFyYW1ldGVycxIPCgd2ZXJz",
            "aW9uGAIgASgFEhIKCmJhdGNoX3NpemUYAyABKAUSEwoLYmF0Y2hfaW5kZXgY",
            "BCABKAUSEAoIYmF0Y2hfaWQYBSABKAUalQIKDU90cFBhcmFtZXRlcnMSDgoG",
            "c2VjcmV0GAEgASgMEgwKBG5hbWUYAiABKAkSDgoGaXNzdWVyGAMgASgJEj4K",
            "CWFsZ29yaXRobRgEIAEoDjIrLmdvb2dsZS5wcm90b2J1Zi5NaWdyYXRpb25Q",
            "YXlsb2FkLkFsZ29yaXRobRI8CgZkaWdpdHMYBSABKA4yLC5nb29nbGUucHJv",
            "dG9idWYuTWlncmF0aW9uUGF5bG9hZC5EaWdpdENvdW50EjcKBHR5cGUYBiAB",
            "KA4yKS5nb29nbGUucHJvdG9idWYuTWlncmF0aW9uUGF5bG9hZC5PdHBUeXBl",
            "Eg8KB2NvdW50ZXIYByABKAMSDgoGcGVyaW9kGAggASgFInkKCUFsZ29yaXRo",
            "bRIZChVBTEdPUklUSE1fVU5TUEVDSUZJRUQQABISCg5BTEdPUklUSE1fU0hB",
            "MRABEhQKEEFMR09SSVRITV9TSEEyNTYQAhIUChBBTEdPUklUSE1fU0hBNTEy",
            "EAMSEQoNQUxHT1JJVEhNX01ENRAEIlUKCkRpZ2l0Q291bnQSGwoXRElHSVRf",
            "Q09VTlRfVU5TUEVDSUZJRUQQABITCg9ESUdJVF9DT1VOVF9TSVgQARIVChFE",
            "SUdJVF9DT1VOVF9FSUdIVBACIkkKB090cFR5cGUSGAoUT1RQX1RZUEVfVU5T",
            "UEVDSUZJRUQQABIRCg1PVFBfVFlQRV9IT1RQEAESEQoNT1RQX1RZUEVfVE9U",
            "UBACQiCqAh1Mb2NhbEJhcmNvZGVTY2FubmVyLkRUTy5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload), global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Parser, new[]{ "OtpParameters", "Version", "BatchSize", "BatchIndex", "BatchId" }, null, new[]{ typeof(global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.Algorithm), typeof(global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.DigitCount), typeof(global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpParameters), global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpParameters.Parser, new[]{ "Secret", "Name", "Issuer", "Algorithm", "Digits", "Type", "Counter", "Period" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  internal sealed partial class MigrationPayload : pb::IMessage<MigrationPayload>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MigrationPayload> _parser = new pb::MessageParser<MigrationPayload>(() => new MigrationPayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MigrationPayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cerberos.TfaImporter.DTO.Proto.AuthDtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MigrationPayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MigrationPayload(MigrationPayload other) : this() {
      otpParameters_ = other.otpParameters_.Clone();
      version_ = other.version_;
      batchSize_ = other.batchSize_;
      batchIndex_ = other.batchIndex_;
      batchId_ = other.batchId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MigrationPayload Clone() {
      return new MigrationPayload(this);
    }

    /// <summary>Field number for the "otp_parameters" field.</summary>
    public const int OtpParametersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpParameters> _repeated_otpParameters_codec
        = pb::FieldCodec.ForMessage(10, global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpParameters.Parser);
    private readonly pbc::RepeatedField<global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpParameters> otpParameters_ = new pbc::RepeatedField<global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpParameters>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpParameters> OtpParameters {
      get { return otpParameters_; }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 2;
    private int version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "batch_size" field.</summary>
    public const int BatchSizeFieldNumber = 3;
    private int batchSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BatchSize {
      get { return batchSize_; }
      set {
        batchSize_ = value;
      }
    }

    /// <summary>Field number for the "batch_index" field.</summary>
    public const int BatchIndexFieldNumber = 4;
    private int batchIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BatchIndex {
      get { return batchIndex_; }
      set {
        batchIndex_ = value;
      }
    }

    /// <summary>Field number for the "batch_id" field.</summary>
    public const int BatchIdFieldNumber = 5;
    private int batchId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BatchId {
      get { return batchId_; }
      set {
        batchId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MigrationPayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MigrationPayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!otpParameters_.Equals(other.otpParameters_)) return false;
      if (Version != other.Version) return false;
      if (BatchSize != other.BatchSize) return false;
      if (BatchIndex != other.BatchIndex) return false;
      if (BatchId != other.BatchId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= otpParameters_.GetHashCode();
      if (Version != 0) hash ^= Version.GetHashCode();
      if (BatchSize != 0) hash ^= BatchSize.GetHashCode();
      if (BatchIndex != 0) hash ^= BatchIndex.GetHashCode();
      if (BatchId != 0) hash ^= BatchId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      otpParameters_.WriteTo(output, _repeated_otpParameters_codec);
      if (Version != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Version);
      }
      if (BatchSize != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BatchSize);
      }
      if (BatchIndex != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(BatchIndex);
      }
      if (BatchId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(BatchId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      otpParameters_.WriteTo(ref output, _repeated_otpParameters_codec);
      if (Version != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Version);
      }
      if (BatchSize != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BatchSize);
      }
      if (BatchIndex != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(BatchIndex);
      }
      if (BatchId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(BatchId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += otpParameters_.CalculateSize(_repeated_otpParameters_codec);
      if (Version != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Version);
      }
      if (BatchSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BatchSize);
      }
      if (BatchIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BatchIndex);
      }
      if (BatchId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BatchId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MigrationPayload other) {
      if (other == null) {
        return;
      }
      otpParameters_.Add(other.otpParameters_);
      if (other.Version != 0) {
        Version = other.Version;
      }
      if (other.BatchSize != 0) {
        BatchSize = other.BatchSize;
      }
      if (other.BatchIndex != 0) {
        BatchIndex = other.BatchIndex;
      }
      if (other.BatchId != 0) {
        BatchId = other.BatchId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            otpParameters_.AddEntriesFrom(input, _repeated_otpParameters_codec);
            break;
          }
          case 16: {
            Version = input.ReadInt32();
            break;
          }
          case 24: {
            BatchSize = input.ReadInt32();
            break;
          }
          case 32: {
            BatchIndex = input.ReadInt32();
            break;
          }
          case 40: {
            BatchId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            otpParameters_.AddEntriesFrom(ref input, _repeated_otpParameters_codec);
            break;
          }
          case 16: {
            Version = input.ReadInt32();
            break;
          }
          case 24: {
            BatchSize = input.ReadInt32();
            break;
          }
          case 32: {
            BatchIndex = input.ReadInt32();
            break;
          }
          case 40: {
            BatchId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MigrationPayload message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      internal enum Algorithm {
        [pbr::OriginalName("ALGORITHM_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("ALGORITHM_SHA1")] Sha1 = 1,
        [pbr::OriginalName("ALGORITHM_SHA256")] Sha256 = 2,
        [pbr::OriginalName("ALGORITHM_SHA512")] Sha512 = 3,
        [pbr::OriginalName("ALGORITHM_MD5")] Md5 = 4,
      }

      internal enum DigitCount {
        [pbr::OriginalName("DIGIT_COUNT_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("DIGIT_COUNT_SIX")] Six = 1,
        [pbr::OriginalName("DIGIT_COUNT_EIGHT")] Eight = 2,
      }

      internal enum OtpType {
        [pbr::OriginalName("OTP_TYPE_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("OTP_TYPE_HOTP")] Hotp = 1,
        [pbr::OriginalName("OTP_TYPE_TOTP")] Totp = 2,
      }

      internal sealed partial class OtpParameters : pb::IMessage<OtpParameters>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<OtpParameters> _parser = new pb::MessageParser<OtpParameters>(() => new OtpParameters());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<OtpParameters> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OtpParameters() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OtpParameters(OtpParameters other) : this() {
          secret_ = other.secret_;
          name_ = other.name_;
          issuer_ = other.issuer_;
          algorithm_ = other.algorithm_;
          digits_ = other.digits_;
          type_ = other.type_;
          counter_ = other.counter_;
          period_ = other.period_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OtpParameters Clone() {
          return new OtpParameters(this);
        }

        /// <summary>Field number for the "secret" field.</summary>
        public const int SecretFieldNumber = 1;
        private pb::ByteString secret_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Secret {
          get { return secret_; }
          set {
            secret_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 2;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "issuer" field.</summary>
        public const int IssuerFieldNumber = 3;
        private string issuer_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Issuer {
          get { return issuer_; }
          set {
            issuer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "algorithm" field.</summary>
        public const int AlgorithmFieldNumber = 4;
        private global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.Algorithm algorithm_ = global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.Algorithm.Unspecified;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.Algorithm Algorithm {
          get { return algorithm_; }
          set {
            algorithm_ = value;
          }
        }

        /// <summary>Field number for the "digits" field.</summary>
        public const int DigitsFieldNumber = 5;
        private global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.DigitCount digits_ = global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.DigitCount.Unspecified;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.DigitCount Digits {
          get { return digits_; }
          set {
            digits_ = value;
          }
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 6;
        private global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpType type_ = global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpType.Unspecified;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpType Type {
          get { return type_; }
          set {
            type_ = value;
          }
        }

        /// <summary>Field number for the "counter" field.</summary>
        public const int CounterFieldNumber = 7;
        private long counter_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long Counter {
          get { return counter_; }
          set {
            counter_ = value;
          }
        }

        /// <summary>Field number for the "period" field.</summary>
        public const int PeriodFieldNumber = 8;
        private int period_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Period {
          get { return period_; }
          set {
            period_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as OtpParameters);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(OtpParameters other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Secret != other.Secret) return false;
          if (Name != other.Name) return false;
          if (Issuer != other.Issuer) return false;
          if (Algorithm != other.Algorithm) return false;
          if (Digits != other.Digits) return false;
          if (Type != other.Type) return false;
          if (Counter != other.Counter) return false;
          if (Period != other.Period) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Secret.Length != 0) hash ^= Secret.GetHashCode();
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (Issuer.Length != 0) hash ^= Issuer.GetHashCode();
          if (Algorithm != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.Algorithm.Unspecified) hash ^= Algorithm.GetHashCode();
          if (Digits != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.DigitCount.Unspecified) hash ^= Digits.GetHashCode();
          if (Type != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpType.Unspecified) hash ^= Type.GetHashCode();
          if (Counter != 0L) hash ^= Counter.GetHashCode();
          if (Period != 0) hash ^= Period.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Secret.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Secret);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Name);
          }
          if (Issuer.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Issuer);
          }
          if (Algorithm != global::LocalBarcodeScanner.DTO.Proto.MigrationPayload.Types.Algorithm.Unspecified) {
            output.WriteRawTag(32);
            output.WriteEnum((int) Algorithm);
          }
          if (Digits != global::LocalBarcodeScanner.DTO.Proto.MigrationPayload.Types.DigitCount.Unspecified) {
            output.WriteRawTag(40);
            output.WriteEnum((int) Digits);
          }
          if (Type != global::LocalBarcodeScanner.DTO.Proto.MigrationPayload.Types.OtpType.Unspecified) {
            output.WriteRawTag(48);
            output.WriteEnum((int) Type);
          }
          if (Counter != 0L) {
            output.WriteRawTag(56);
            output.WriteInt64(Counter);
          }
          if (Period != 0) {
            output.WriteRawTag(64);
            output.WriteInt32(Period);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Secret.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Secret);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Name);
          }
          if (Issuer.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Issuer);
          }
          if (Algorithm != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.Algorithm.Unspecified) {
            output.WriteRawTag(32);
            output.WriteEnum((int) Algorithm);
          }
          if (Digits != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.DigitCount.Unspecified) {
            output.WriteRawTag(40);
            output.WriteEnum((int) Digits);
          }
          if (Type != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpType.Unspecified) {
            output.WriteRawTag(48);
            output.WriteEnum((int) Type);
          }
          if (Counter != 0L) {
            output.WriteRawTag(56);
            output.WriteInt64(Counter);
          }
          if (Period != 0) {
            output.WriteRawTag(64);
            output.WriteInt32(Period);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Secret.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Secret);
          }
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (Issuer.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Issuer);
          }
          if (Algorithm != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.Algorithm.Unspecified) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Algorithm);
          }
          if (Digits != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.DigitCount.Unspecified) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Digits);
          }
          if (Type != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpType.Unspecified) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          if (Counter != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Counter);
          }
          if (Period != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Period);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(OtpParameters other) {
          if (other == null) {
            return;
          }
          if (other.Secret.Length != 0) {
            Secret = other.Secret;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.Issuer.Length != 0) {
            Issuer = other.Issuer;
          }
          if (other.Algorithm != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.Algorithm.Unspecified) {
            Algorithm = other.Algorithm;
          }
          if (other.Digits != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.DigitCount.Unspecified) {
            Digits = other.Digits;
          }
          if (other.Type != global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpType.Unspecified) {
            Type = other.Type;
          }
          if (other.Counter != 0L) {
            Counter = other.Counter;
          }
          if (other.Period != 0) {
            Period = other.Period;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Secret = input.ReadBytes();
                break;
              }
              case 18: {
                Name = input.ReadString();
                break;
              }
              case 26: {
                Issuer = input.ReadString();
                break;
              }
              case 32: {
                Algorithm = (global::LocalBarcodeScanner.DTO.Proto.MigrationPayload.Types.Algorithm) input.ReadEnum();
                break;
              }
              case 40: {
                Digits = (global::LocalBarcodeScanner.DTO.Proto.MigrationPayload.Types.DigitCount) input.ReadEnum();
                break;
              }
              case 48: {
                Type = (global::LocalBarcodeScanner.DTO.Proto.MigrationPayload.Types.OtpType) input.ReadEnum();
                break;
              }
              case 56: {
                Counter = input.ReadInt64();
                break;
              }
              case 64: {
                Period = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Secret = input.ReadBytes();
                break;
              }
              case 18: {
                Name = input.ReadString();
                break;
              }
              case 26: {
                Issuer = input.ReadString();
                break;
              }
              case 32: {
                Algorithm = (global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.Algorithm) input.ReadEnum();
                break;
              }
              case 40: {
                Digits = (global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.DigitCount) input.ReadEnum();
                break;
              }
              case 48: {
                Type = (global::Cerberos.TfaImporter.DTO.Proto.MigrationPayload.Types.OtpType) input.ReadEnum();
                break;
              }
              case 56: {
                Counter = input.ReadInt64();
                break;
              }
              case 64: {
                Period = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
